function model = trainSvm(features, labels)
%TRAINSVM Train an SVM classifier using the training features and labels
%   This function trains an SVM classifier with the training feature vector
%   @features and the training label vector @labels. To allow deterministic
%   results, MATLAB's rng is initialized and randomsearch applied during
%   hyperparameter optimization.

% Use Parallel Pool if availabe
parallelUse = canUseParallelPool;

% Reduce number of iterations for matlab online
iterNum = 200;
if strcmp(getenv('USER'), 'mluser') & strcmp(computer(),'GLNXA64') == 1
    iterNum = 20;
end

% initialize MATLAB rng to yield repeatable results
rng(0)

model = fitcsvm(features, labels, ...
    'KernelFunction', 'gaussian', ...
    'KernelScale', 'auto', ...
    'BoxConstraint', 1, ...
    'Standardize', true, ...
    'RemoveDuplicates', true, ... % consider removal, no large impact
    'OptimizeHyperparameters', 'auto', ...
    'HyperparameterOptimizationOptions', struct( ...
        'Optimizer', 'randomsearch', ...
        'MaxObjectiveEvaluations', iterNum, ... 
        'Verbose', 0, ...
        'Repartition', true, ...
        'ShowPlots', false, ...
        'UseParallel', parallelUse, ... % enable for large number of objectives
        'Kfold', 5));
end

